######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 5 20:47:24 2007
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += . \
        ../../common \
        ../../lib
# include also the directory where uic generated header files are
# in case of shadow builds
INCLUDEPATH += . \
        $$OUT_PWD/../../common \
        ../../common \
        ../../lib/common \
        ../../lib/facebook \
        ../../lib/flickr \
        ../../lib/gpicasa
CONFIG += qt
QT += core gui network xml

PRE_TARGETDEPS += $$OUT_PWD/../../common/libcommon.a \
        $$OUT_PWD/../../lib/libqmediashare.a
LIBS += $$OUT_PWD/../../common/libcommon.a \
        $$OUT_PWD/../../lib/libqmediashare.a

# Input
HEADERS += test.h
FORMS += test.ui
SOURCES += main.cpp test.cpp
