######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 5 20:47:24 2007
######################################################################

TEMPLATE = app
TARGET = flickrlibtest
DEPENDPATH += . \
        ../../common \
        ../../lib
INCLUDEPATH += . \
        ../../common \
        ../../lib/common \
        ../../lib/flickr
CONFIG += qt
QT += core network xml

PRE_TARGETDEPS += $$OUT_PWD/../../common/libcommon.a \
        $$OUT_PWD/../../lib/libqmediashare.a
LIBS += $$OUT_PWD/../../common/libcommon.a \
        $$OUT_PWD/../../lib/libqmediashare.a

# Input
HEADERS += flickrlibtest.h
#FORMS += test.ui
SOURCES += main.cpp flickrlibtest.cpp
